# Generated by Django 3.1.5 on 2021-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210309_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='googlemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googleurl', models.URLField(blank=True)),
            ],
        ),
    ]
