# Generated by Django 3.1.5 on 2021-03-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_techproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='bizProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/pics')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
