# Generated by Django 3.1.5 on 2021-03-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_bizproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='portfolio/pics'),
        ),
    ]
