# Generated by Django 3.1.5 on 2021-03-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemap',
            name='googleurl',
            field=models.URLField(max_length=2000),
        ),
    ]
